#ifndef APP_CONFIG_H_INCLUDED
#define APP_CONFIG_H_INCLUDED

/*
 *  Macro riguardanti la configurazione dell'applicazione
 */

#define APP_CONFIG_FIRMWARE_VERSION_MAJOR 2
#define APP_CONFIG_FIRMWARE_VERSION_MINOR 2
#define APP_CONFIG_FIRMWARE_VERSION_PATCH 1

#define APP_CONFIG_BASE_TASK_STACK_SIZE 512

#define APP_CONFIG_HARDWARE_MODEL EASYCONNECT_DEVICE_MOTOR_PERIPHERAL

#endif
